/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * ----------------------------------
 * This file was generated by ISL Compiler.
 * Source: dungeon.isl.md
 * Edit the ISL file instead.
 */

import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { PageNavigationEnum } from './domain-core';
import { isEditorPlaytestActive, setEditorPlaytestActive } from './editor/editor-playtest-session.js';
import DungeonBoard from './dungeon-board';
import DungeonGameShell from './dungeon-game-shell.jsx';
import DungeonActionBar from './dungeon-action-bar.jsx';
import DungeonHeroHud from './dungeon-hero-hud.jsx';
import DungeonTopBar from './dungeon-top-bar.jsx';
import DungeonHeroOrder from './dungeon-hero-order';
import { useTurnLogic } from './dungeon-use-turn-logic';
import { usePathfinding } from './dungeon-use-pathfinding';
import { useCombatLogic } from './dungeon-use-combat';
import { useHeroStats } from './dungeon-use-hero-stats';
import { useFogOfWar } from './dungeon-use-fog-of-war';
import { useVisibilityCalc } from './dungeon-use-visibility-calc';
import { useDungeonMonsters } from './dungeon-use-monsters';
import CombatResultModal from './dungeon-combat-result-modal';
import { useSecretPassages } from './dungeon-use-secret-passages';
import { useTreasureSearch } from './dungeon-use-treasure';
import { useInventoryLogic } from './dungeon-use-inventory-logic';
import { useItemLogic } from './dungeon-use-item-logic';
import { useMapInteraction } from './dungeon-use-map-interaction';
import DungeonNotification from './dungeon-notification';
import TreasureCardModal from './dungeon-treasure-card-modal';
import DungeonInventoryModal from './dungeon-inventory-modal';
import { useTraps } from './dungeon-use-traps';
import DungeonGameOver from './dungeon-game-over';
import DungeonSpellSelectionModal from './dungeon-spell-selection-modal';
import { useMagicLogic } from './dungeon-use-magic';
import DungeonMissionSummary from './dungeon-mission-summary';
import { useCampaignManager } from './dungeon-use-campaign-manager';
import DungeonSpellCastModal from './dungeon-spell-cast-modal';
import { useMonsterAI } from './dungeon-use-monster-ai';
import { useDungeonSessionManager } from './dungeon-use-session-manager';
import DungeonScriptDialog from './dungeon-script-dialog';
import {
    mergeMissionHeroesIntoCampaignRoster,
    missionHeroesNeedSpellSelection,
    filterHeroesForSpellSelection
} from './mission-party.js';
import { playDungeonSfx, setDungeonAudioMuted, primeFootstepsAudio } from './dungeon-audio.js';

const BACKGROUND_MUSIC_VOLUME = 0.25;
const AUDIO_MUTED_STORAGE_KEY = 'dungeonAudioMuted';

function readAudioMutedFromStorage() {
    try {
        return localStorage.getItem(AUDIO_MUTED_STORAGE_KEY) === 'true';
    } catch {
        return false;
    }
}

export default function Dungeon({
    gameSession,
    onChangePageView,
    onUpdateSession,
    staticMonsters,
    staticVisibilityMap,
    staticEquipment,
    staticItems,
    staticSpells,
    treasureDeck
}) {
    const [isMissionInitialized, setIsMissionInitialized] = useState(false);
    const [isInventoryOpen, setIsInventoryOpen] = useState(false);
    const [audioMuted, setAudioMuted] = useState(readAudioMutedFromStorage);
    const [isSpellSelectionRequired, setIsSpellSelectionRequired] = useState(false);
    const [isSpellCastModalOpen, setIsSpellCastModalOpen] = useState(false);
    const [isMissionSummaryOpen, setIsMissionSummaryOpen] = useState(false);
    const [isGameOverOpen, setIsGameOverOpen] = useState(false);
    const [targetingSpell, setTargetingSpell] = useState(null);
    const [targetingItem, setTargetingItem] = useState(null);
    const [drawnTreasureCard, setDrawnTreasureCard] = useState(null);
    const [notificationMessage, setNotificationMessage] = useState(null);
    const [scriptDialogQueue, setScriptDialogQueue] = useState([]);

    const bgMusicRef = useRef(null);
    useEffect(() => {
        const audio = new Audio('/audio/gioco.mp3');
        audio.loop = true;
        audio.volume = audioMuted ? 0 : BACKGROUND_MUSIC_VOLUME;
        bgMusicRef.current = audio;
        audio.play()
            .then(() => primeFootstepsAudio())
            .catch(() => {});
        return () => {
            audio.pause();
            audio.src = '';
        };
    }, []);

    useEffect(() => {
        setDungeonAudioMuted(audioMuted);
        if (bgMusicRef.current) {
            bgMusicRef.current.volume = audioMuted ? 0 : BACKGROUND_MUSIC_VOLUME;
        }
    }, [audioMuted]);

    const toggleAudioMuted = useCallback(() => {
        setAudioMuted((prev) => {
            const next = !prev;
            try {
                localStorage.setItem(AUDIO_MUTED_STORAGE_KEY, next ? 'true' : 'false');
            } catch {
                /* ignore */
            }
            return next;
        });
    }, []);

    const hooksFogOfWar = useFogOfWar({ gameSession, staticVisibilityMap });
    const boardVisibilityMap = hooksFogOfWar.fogVisibilityMap;
    const hooksVisibilityCalc = useVisibilityCalc({ gameSession, visibilityMap: boardVisibilityMap });

    const enqueueScriptDialogs = useCallback((messages) => {
        if (!messages?.length) return;
        setScriptDialogQueue((q) => [...q, ...messages]);
    }, []);

    const hooksSessionManager = useDungeonSessionManager({
        gameSession,
        onUpdateSession,
        onNotify: setNotificationMessage,
        onScriptBlockingDialog: enqueueScriptDialogs,
        fogOfWarLogic: hooksFogOfWar,
        staticEquipment,
        staticItems,
        scriptVisibilityMap: boardVisibilityMap,
        doorVisibilityMap: staticVisibilityMap,
    });

    const hooksInventoryLogic = useInventoryLogic({ staticEquipment, sessionManager: hooksSessionManager });
    const hooksItemLogic = useItemLogic({ staticItems, sessionManager: hooksSessionManager });
    const hooksCampaignManager = useCampaignManager({ onNotify: setNotificationMessage });
    const hooksCombatLogic = useCombatLogic();
    const hooksHeroStats = useHeroStats({ staticEquipment });

    const areMonstersVisible = useMemo(() => {
        if (!gameSession?.monsters || !boardVisibilityMap?.data) return false;
        return gameSession.monsters.some(m => {
            const cell = boardVisibilityMap.data.find(c => c.x === m.x && c.y === m.y);
            return cell && !cell.fog;
        });
    }, [gameSession?.monsters, boardVisibilityMap]);

    const spellSelectionHeroes = useMemo(
        () => filterHeroesForSpellSelection(gameSession?.heroes),
        [gameSession?.heroes]
    );

    const prevMonstersVisibleRef = useRef(false);
    useEffect(() => {
        if (areMonstersVisible && !prevMonstersVisibleRef.current) {
            playDungeonSfx('/audio/mostri.mp3');
        }
        prevMonstersVisibleRef.current = areMonstersVisible;
    }, [areMonstersVisible, playDungeonSfx]);

    useEffect(() => {
        if (!gameSession?.lastAttack?.combatResult) return;
        const { damageDealt } = gameSession.lastAttack.combatResult;
        const isRanged = !!gameSession.lastAttack.isRanged;
        const src = damageDealt > 0
            ? (isRanged ? '/audio/tiro.mp3' : '/audio/danno.mp3')
            : (isRanged ? '/audio/tirom.mp3' : '/audio/parata.mp3');
        playDungeonSfx(src);
    }, [gameSession?.lastAttack, playDungeonSfx]);

    const hooksMonsters = useDungeonMonsters({
        gameSession,
        visibilityMap: boardVisibilityMap,
        onUpdateSession,
        onNotify: setNotificationMessage,
        monsterDefinitions: staticMonsters
    });

    const turnLogicActionsRef = useRef({
        markActionDone: () => {},
        forceTurnExhausted: () => {}
    });

    const monsterAIRef = useRef(null);

    const hooksTraps = useTraps({
        gameSession,
        visibilityMap: boardVisibilityMap,
        areMonstersVisible,
        onNotify: setNotificationMessage,
        onActionDone: () => turnLogicActionsRef.current.markActionDone(),
        onForceTurnEnd: () => turnLogicActionsRef.current.forceTurnExhausted(),
        sessionManager: hooksSessionManager
    });

    const hooksSecretPassages = useSecretPassages({
        gameSession,
        visibilityMap: boardVisibilityMap,
        onNotify: setNotificationMessage,
        onActionDone: () => turnLogicActionsRef.current.markActionDone(),
        onForceTurnEnd: () => turnLogicActionsRef.current.forceTurnExhausted(),
        sessionManager: hooksSessionManager
    });

    const foundPassages = useMemo(() => hooksSecretPassages.getFoundPassages().visiblePassages, [hooksSecretPassages]);

    const hooksPathfinding = usePathfinding({
        gameSession,
        visibilityMap: staticVisibilityMap,
        foundPassages
    });

    const hooksMapInteraction = useMapInteraction({
        gameSession,
        foundPassages,
        sessionManager: hooksSessionManager
    });

    const hooksTurnLogic = useTurnLogic({
        gameSession,
        visibilityMap: boardVisibilityMap,
        onNotify: setNotificationMessage,
        trapsLogic: hooksTraps,
        heroStatsLogic: hooksHeroStats,
        hooksPathfinding,
        combatLogic: hooksCombatLogic,
        mapInteractionLogic: hooksMapInteraction,
        visibilityCalc: hooksVisibilityCalc,
        sessionManager: hooksSessionManager
    });

    useEffect(() => {
        turnLogicActionsRef.current.markActionDone = hooksTurnLogic.markActionDone;
        turnLogicActionsRef.current.forceTurnExhausted = hooksTurnLogic.forceTurnExhausted;
    }, [hooksTurnLogic.markActionDone, hooksTurnLogic.forceTurnExhausted]);

    const handleTreasureCardDrawn = useCallback((card) => {
        setDrawnTreasureCard(card);
    }, []);

    const handleWanderingMonster = useCallback((x, y) => {
        const newMonster = hooksMonsters.spawnWanderingMonster(x, y);
        if (!newMonster) return;
        const hero = gameSession?.heroes?.find(h => h.x === x && h.y === y);
        if (!hero) return;
        const ai = monsterAIRef.current;
        if (ai?.performInstantAttack) {
            void ai.performInstantAttack(newMonster, hero);
        }
    }, [hooksMonsters, gameSession]);

    const hooksTreasure = useTreasureSearch({
        gameSession,
        visibilityMap: boardVisibilityMap,
        onNotify: setNotificationMessage,
        onActionDone: () => hooksTurnLogic.markActionDone(),
        onForceTurnEnd: () => hooksTurnLogic.forceTurnExhausted(),
        sessionManager: hooksSessionManager,
        onTreasureCardDrawn: handleTreasureCardDrawn,
        onWanderingMonster: handleWanderingMonster
    });

    const hooksMagicLogic = useMagicLogic({
        gameSession,
        onUpdateSession,
        onNotify: setNotificationMessage,
        onActionDone: () => hooksTurnLogic.markActionDone(),
        staticSpells,
        combatLogic: hooksCombatLogic,
        mapInteractionLogic: hooksMapInteraction,
        fogOfWarLogic: hooksFogOfWar,
        heroStatsLogic: hooksHeroStats,
        onScriptBlockingDialog: enqueueScriptDialogs,
    });

    const hooksMonsterAI = useMonsterAI({
        gameSession,
        visibilityMap: boardVisibilityMap,
        onNotify: setNotificationMessage,
        pathfinding: hooksPathfinding,
        combatLogic: hooksCombatLogic,
        heroStatsLogic: hooksHeroStats,
        sessionManager: hooksSessionManager
    });

    useEffect(() => {
        monsterAIRef.current = hooksMonsterAI;
    }, [hooksMonsterAI]);

    const lastHudHeroRef = useRef(null);

    const currentHero = useMemo(() => {
        return gameSession?.heroes?.find(
            h => h.turnOrder === gameSession.currentTurn && (h.currentBody || 0) > 0
        );
    }, [gameSession?.heroes, gameSession?.currentTurn]);

    if (currentHero) {
        lastHudHeroRef.current = currentHero;
    }

    const participatingHeroCount = useMemo(
        () => (gameSession?.heroes || []).filter((h) => (h.turnOrder ?? 0) > 0).length,
        [gameSession?.heroes]
    );

    const isMonsterPhase = useMemo(() => {
        if (!gameSession?.isHeroOrderConfirmed || participatingHeroCount <= 0) {
            return false;
        }
        return (gameSession.currentTurn ?? 0) > participatingHeroCount;
    }, [
        gameSession?.isHeroOrderConfirmed,
        gameSession?.currentTurn,
        participatingHeroCount,
    ]);

    const hudHero = currentHero ?? (isMonsterPhase ? lastHudHeroRef.current : null);

    const [isCoarsePointer, setIsCoarsePointer] = useState(() => {
        if (typeof window === 'undefined') return false;
        return window.matchMedia('(pointer: coarse)').matches;
    });

    useEffect(() => {
        if (typeof window === 'undefined') return;
        const mq = window.matchMedia('(pointer: coarse)');
        const onChange = () => setIsCoarsePointer(mq.matches);
        mq.addEventListener('change', onChange);
        return () => mq.removeEventListener('change', onChange);
    }, []);

    const currentHeroStats = useMemo(() => {
        return hudHero ? hooksHeroStats.calculateStats(hudHero) : null;
    }, [hudHero, hooksHeroStats]);

    const missionObjectiveCompleted = hooksTurnLogic.isMissionObjectiveCompleted;

    useEffect(() => {
        if (!isMissionInitialized && gameSession) {
            hooksSessionManager.initializeMission(treasureDeck);
            setIsMissionInitialized(true);
        }
    }, [isMissionInitialized, gameSession, hooksSessionManager, treasureDeck]);

    useEffect(() => {
        if (gameSession && gameSession.isHeroOrderConfirmed === false) {
            setIsSpellSelectionRequired(false);
        }
    }, [gameSession?.isHeroOrderConfirmed]);

    const handleConfirmHeroOrder = useCallback((orderedHeroIds) => {
        hooksSessionManager.confirmHeroOrder(orderedHeroIds);
        const roster = gameSession?.heroes ?? [];
        const idOrder = Array.isArray(orderedHeroIds) ? orderedHeroIds : [];
        const orderedHeroes = idOrder
            .map((id) => roster.find((h) => Number(h.heroId) === Number(id)))
            .filter(Boolean);
        const partyForSpells = orderedHeroes.length > 0 ? orderedHeroes : roster;
        setIsSpellSelectionRequired(missionHeroesNeedSpellSelection(partyForSpells));
    }, [hooksSessionManager, gameSession]);

    useEffect(() => {
        if (!gameSession || !isMissionInitialized || gameSession.isHeroOrderConfirmed) return;
        const list = gameSession.heroes;
        if (!Array.isArray(list) || list.length !== 1) return;
        handleConfirmHeroOrder([list[0].heroId]);
    }, [gameSession, isMissionInitialized, handleConfirmHeroOrder]);

    const confirmSpellSelection = useCallback((selection) => {
        if (!gameSession) return;
        const updatedHeroes = gameSession.heroes.map(h => {
            if (selection.has(h.heroId)) {
                return { ...h, availableSpells: selection.get(h.heroId) };
            }
            return h;
        });
        onUpdateSession({ ...gameSession, heroes: updatedHeroes });
        setIsSpellSelectionRequired(false);
    }, [gameSession, onUpdateSession]);

    const closeCombatResult = useCallback(() => {
        hooksSessionManager.clearLastAttack();
    }, [hooksSessionManager]);

    const closeTreasureCardModal = useCallback(() => {
        if (drawnTreasureCard) {
            hooksTreasure.applyTreasureEffect(drawnTreasureCard);
        }
        setDrawnTreasureCard(null);
    }, [drawnTreasureCard, hooksTreasure]);

    const processMissionEnd = useCallback((isVictory) => {
        if (!gameSession) return;
        const preEndHeroVitalsById = {};
        gameSession.heroes.forEach(h => {
            preEndHeroVitalsById[h.heroId] = { currentBody: h.currentBody, currentMind: h.currentMind };
        });

        const rosterBackup = gameSession.preMissionHeroesBackup;

        const scriptResult = hooksSessionManager.executeMissionScripts({
            baseSession: gameSession,
            eventType: 7,
            context: { isVictory }
        });

        const missionEndSession = (scriptResult && scriptResult.handled && scriptResult.session) ? scriptResult.session : gameSession;

        let heroesToPersist;
        if (Array.isArray(rosterBackup) && rosterBackup.length > 0) {
            const merged = mergeMissionHeroesIntoCampaignRoster(rosterBackup, missionEndSession.heroes);
            heroesToPersist = merged.map(h => {
                const vitals = preEndHeroVitalsById[h.heroId];
                if (vitals) {
                    return { ...h, currentBody: vitals.currentBody, currentMind: vitals.currentMind };
                }
                return h;
            });
        } else {
            heroesToPersist = missionEndSession.heroes.map(h => {
                const vitals = preEndHeroVitalsById[h.heroId];
                if (vitals) {
                    return { ...h, currentBody: vitals.currentBody, currentMind: vitals.currentMind };
                }
                return h;
            });
        }

        const savedCampaign = hooksCampaignManager.loadCampaign();
        const preservedMissionIndex = savedCampaign ? savedCampaign.nextMissionIndex : 0;

        if (isEditorPlaytestActive()) {
            setEditorPlaytestActive(false);
            hooksCampaignManager.saveCampaign(heroesToPersist, preservedMissionIndex);
            onChangePageView(PageNavigationEnum.EDITOR_GAME);
            return;
        }

        let nextMissionIndex = preservedMissionIndex;
        if (isVictory) {
            const possibleNext = (missionEndSession.currentMissionIndex || 0) + 1;
            nextMissionIndex = Math.max(preservedMissionIndex, possibleNext);
        }

        hooksCampaignManager.saveCampaign(heroesToPersist, nextMissionIndex);
        onChangePageView(PageNavigationEnum.PLAY_GAME);
    }, [gameSession, hooksSessionManager, hooksCampaignManager, onChangePageView]);

    const leaveDungeonAfterRetreat = useCallback(() => {
        processMissionEnd(false);
    }, [processMissionEnd]);

    const handleExitMapFromOptions = useCallback(() => {
        if (!window.confirm('Uscire dalla missione? Verrà registrata una ritirata (missione non completata).')) {
            return;
        }
        leaveDungeonAfterRetreat();
    }, [leaveDungeonAfterRetreat]);

    const completeMission = useCallback(() => {
        setIsMissionSummaryOpen(false);
        processMissionEnd(true);
    }, [processMissionEnd]);

    useEffect(() => {
        if (!gameSession || !isMissionInitialized || !gameSession.isHeroOrderConfirmed) return;

        const currentTurnHero = gameSession.heroes.find(h => h.turnOrder === gameSession.currentTurn);
        if (currentTurnHero && (currentTurnHero.currentBody <= 0 || currentTurnHero.isEscaped)) {
            hooksTurnLogic.endTurn();
            return;
        }

        const activeHeroes = gameSession.heroes.filter(h => h.currentBody > 0);
        if (activeHeroes.length === 0) {
            setIsGameOverOpen(true);
            return;
        }

        const escapedHeroes = activeHeroes.filter(h => h.isEscaped);
        if (activeHeroes.length > 0 && activeHeroes.length === escapedHeroes.length) {
            if (missionObjectiveCompleted) {
                setIsMissionSummaryOpen(true);
            } else {
                leaveDungeonAfterRetreat();
            }
            return;
        }

        if (
            participatingHeroCount > 0 &&
            gameSession.currentTurn > participatingHeroCount
        ) {
            hooksMonsterAI.runMonsterTurn();
        }
    }, [gameSession?.currentTurn, isMissionInitialized, gameSession?.isHeroOrderConfirmed, gameSession?.heroes, participatingHeroCount, hooksTurnLogic, missionObjectiveCompleted, leaveDungeonAfterRetreat, hooksMonsterAI]);

    const handleGameOverExit = useCallback(() => {
        setIsGameOverOpen(false);
        onChangePageView(PageNavigationEnum.MAIN_MENU);
    }, [onChangePageView]);

    const handleUseItem = useCallback((heroId, itemId) => {
        const item = staticItems?.find(i => i.id === itemId);
        const requiresMonsterTarget = item?.targetType === "Monster" || item?.acqua === true;
        if (requiresMonsterTarget) {
            setTargetingItem(item);
            setIsInventoryOpen(false);
            setNotificationMessage(`Seleziona un mostro bersaglio per ${item.nome}`);
        } else {
            hooksItemLogic.useItem(heroId, itemId, gameSession, null);
        }
    }, [staticItems, hooksItemLogic, gameSession]);

    const handleCastSpell = useCallback((spellId) => {
        const spell = staticSpells?.find(s => s.id === spellId);
        if (spell?.targetType === "Self") {
            if (!currentHero) {
                setNotificationMessage("Nessun eroe attivo disponibile.");
                return;
            }
            hooksMagicLogic.castSpell(spellId, currentHero.heroId, null, null, null);
            setIsSpellCastModalOpen(false);
        } else if (spell) {
            setTargetingSpell(spell);
            setIsSpellCastModalOpen(false);
            if (spell.effetto === "Genio") {
                setNotificationMessage("Il Genio attende: Clicca su un mostro per attaccare (5 dadi) o su una porta per aprirla.");
            } else {
                setNotificationMessage(`Seleziona un bersaglio per ${spell.nome} (Clicca sulla mappa o su un mostro)`);
            }
        }
    }, [staticSpells, currentHero, hooksMagicLogic]);

    const handleBoardClick = useCallback((x, y) => {
        if (isMonsterPhase || hooksMonsterAI.isMonsterTurnInProgress) {
            return;
        }
        if (targetingSpell) {
            if (!currentHero) {
                setNotificationMessage("Nessun eroe attivo disponibile.");
                return;
            }
            if (targetingSpell.targetType === "Point") {
                hooksMagicLogic.castSpell(targetingSpell.id, null, null, x, y);
                setTargetingSpell(null);
                setNotificationMessage(null);
            } else if (targetingSpell.targetType === "Hero") {
                const hero = gameSession?.heroes?.find(h => h.x === x && h.y === y);
                if (hero) {
                    hooksMagicLogic.castSpell(targetingSpell.id, hero.heroId, null, x, y);
                    setTargetingSpell(null);
                    setNotificationMessage(null);
                } else {
                    setNotificationMessage("Devi selezionare un Eroe come bersaglio!");
                }
            } else {
                setNotificationMessage("Bersaglio non valido per questo incantesimo!");
            }
        } else {
            hooksTurnLogic.handleBoardClick(x, y);
        }
    }, [targetingSpell, currentHero, hooksMagicLogic, gameSession, hooksTurnLogic, isMonsterPhase, hooksMonsterAI.isMonsterTurnInProgress]);

    const handleMonsterClick = useCallback((monsterId) => {
        if (isMonsterPhase || hooksMonsterAI.isMonsterTurnInProgress) {
            return;
        }
        if (targetingItem) {
            if (!currentHero) {
                setNotificationMessage("Nessun eroe attivo disponibile.");
                return;
            }
            hooksItemLogic.useItem(currentHero.heroId, targetingItem.id, gameSession, monsterId);
            setTargetingItem(null);
            setNotificationMessage(null);
            return;
        }
        if (targetingSpell) {
            if (!currentHero) {
                setNotificationMessage("Nessun eroe attivo disponibile.");
                return;
            }
            const monster = gameSession?.monsters?.find(m => m.id === monsterId);
            if (!monster) {
                setNotificationMessage("Mostro bersaglio non valido.");
                return;
            }
            if (targetingSpell.targetType === "Monster" || targetingSpell.effetto === "Genio") {
                hooksMagicLogic.castSpell(targetingSpell.id, null, monsterId, null, null);
                setTargetingSpell(null);
                setNotificationMessage(null);
            } else {
                setNotificationMessage("Questo incantesimo non può essere lanciato su un mostro!");
            }
        } else {
            hooksTurnLogic.handleMonsterClick(monsterId);
        }
    }, [targetingItem, targetingSpell, currentHero, hooksItemLogic, gameSession, hooksMagicLogic, hooksTurnLogic, isMonsterPhase, hooksMonsterAI.isMonsterTurnInProgress]);

    const cancelTargeting = useCallback(() => {
        setTargetingSpell(null);
        setTargetingItem(null);
        setNotificationMessage("Lancio incantesimo annullato.");
    }, []);

    const handleDisarmTrap = useCallback(() => {
        if (!currentHero) return;
        const canDisarm = hooksHeroStats.calculateStats(currentHero).canDisarmTraps;
        hooksTraps.disarmAdjacentTrap(currentHero.x, currentHero.y, canDisarm, (trapState) => {
            const cell = gameSession?.currentMap?.grid?.find((c) => c.x === trapState.x && c.y === trapState.y);
            const trpl = cell?.trpl;
            if (!trpl || trpl.tipo <= 0) return;
            hooksSessionManager.resolveTrapEffectOnCurrentHero(trpl.tipo, trpl.rccadex, trpl.rccadey);
        });
    }, [currentHero, hooksHeroStats, hooksTraps, gameSession, hooksSessionManager]);

    const canDisarmTrap = useMemo(() => {
        if (!currentHero) return false;
        const stats = hooksHeroStats.calculateStats(currentHero);
        if (!stats.canDisarmTraps) return false;
        const adjTrap = hooksTraps.getAdjacentDisarmableTrap(currentHero.x, currentHero.y);
        return !!adjTrap;
    }, [currentHero, hooksHeroStats, hooksTraps]);

    const triggeredTraps = useMemo(() => {
        return hooksTraps.getTriggeredTraps().filter(t => t.status !== 'DISARMED');
    }, [hooksTraps]);

    const showHeroHud =
        gameSession?.isHeroOrderConfirmed &&
        hudHero &&
        hudHero.currentBody > 0;

    const showActionBar = showHeroHud && !hudHero.isEscaped;

    const uiChromeDisabled =
        isMonsterPhase || hooksMonsterAI.isMonsterTurnInProgress;

    const heroClassKey = hudHero?.hero?.classe?.toLowerCase() || '';
    const canUseMagic = ['mago', 'elfo'].includes(heroClassKey);
    const turnPhase = hooksTurnLogic.turnPhase;
    const magicDisabled =
        uiChromeDisabled ||
        turnPhase?.HasPerformedAction === true ||
        hooksTurnLogic.isMoving ||
        !!targetingSpell;

    const movementReachableCells =
        isCoarsePointer && !uiChromeDisabled && !targetingSpell && !targetingItem
            ? hooksTurnLogic.reachableMovementCells
            : [];

    const actionBarProps = {
        currentHero: hudHero,
        currentHeroStats,
        movementPoints: hooksTurnLogic.movementPoints,
        turnPhase,
        chromeDisabled: uiChromeDisabled,
        canOpenDoor: !!hooksTurnLogic.canOpenDoor,
        isTargeting: !!targetingSpell,
        isMoving: hooksTurnLogic.isMoving,
        onEndTurn: hooksTurnLogic.endTurn,
        onSearchPassages: hooksSecretPassages.searchPassages,
        onSearchTreasure: hooksTreasure.searchTreasure,
        onSearchTraps: hooksTraps.searchTraps,
        canDisarmTrap,
        onDisarmTrap: handleDisarmTrap,
        onOpenMagic: () => setIsSpellCastModalOpen(true),
        onOpenInventory: () => setIsInventoryOpen(true),
        onCancelTargeting: cancelTargeting,
        onOpenDoor: hooksTurnLogic.handleOpenDoor,
        audioMuted,
        onToggleAudioMuted: toggleAudioMuted,
        onExitMap: handleExitMapFromOptions,
    };

    return (
        <DungeonGameShell
            topBar={
                showHeroHud ? (
                    <DungeonTopBar
                        currentHero={hudHero}
                        movementPoints={hooksTurnLogic.movementPoints}
                        currentTurn={gameSession?.currentTurn}
                        canUseMagic={canUseMagic}
                        magicDisabled={magicDisabled}
                        chromeDisabled={uiChromeDisabled}
                        onOpenInventory={() => setIsInventoryOpen(true)}
                        onOpenMagic={() => setIsSpellCastModalOpen(true)}
                        audioMuted={audioMuted}
                        onToggleAudioMuted={toggleAudioMuted}
                        onExitMap={handleExitMapFromOptions}
                    />
                ) : null
            }
            heroHud={
                showHeroHud ? (
                    <DungeonHeroHud
                        currentHero={hudHero}
                        currentHeroStats={currentHeroStats}
                        chromeDisabled={uiChromeDisabled}
                    />
                ) : null
            }
            board={
            <div className="relative p-1 sm:p-2 bg-stone-900 border-2 border-amber-900/50 rounded-lg shadow-2xl">
                <div className="absolute top-0 left-0 w-8 h-8 border-t-4 border-l-4 border-amber-600 rounded-tl-lg pointer-events-none" />
                <div className="absolute top-0 right-0 w-8 h-8 border-t-4 border-r-4 border-amber-600 rounded-tr-lg pointer-events-none" />
                <div className="absolute bottom-0 left-0 w-8 h-8 border-b-4 border-l-4 border-amber-600 rounded-bl-lg pointer-events-none" />
                <div className="absolute bottom-0 right-0 w-8 h-8 border-b-4 border-r-4 border-amber-600 rounded-br-lg pointer-events-none" />

                <div className="dungeon-chrome-label absolute -top-4 left-1/2 -translate-x-1/2 px-6 py-1 bg-stone-800 border-2 border-amber-700 rounded text-amber-500 text-sm font-serif tracking-widest shadow-md pointer-events-none">
                    DUNGEON
                </div>

                <DungeonBoard
                    gameSession={gameSession}
                    boardVisibilityMap={boardVisibilityMap}
                    onCellClick={handleBoardClick}
                    onCellHover={hooksTurnLogic.handleBoardHover}
                    onMonsterClick={handleMonsterClick}
                    hoveredPath={hooksTurnLogic.hoveredPath}
                    hoveredPathVariant={hooksTurnLogic.hoveredPathVariant}
                    movementReachableCells={movementReachableCells}
                    secretPassages={foundPassages}
                    treasures={hooksTreasure.getFoundTreasures()}
                    triggeredTraps={triggeredTraps}
                    targetingSpell={targetingSpell}
                    targetingItem={targetingItem}
                    visibilityCalc={hooksVisibilityCalc}
                    canAttackMonsterAt={hooksTurnLogic.canAttackMonsterAt}
                />

            </div>
            }
            actions={showActionBar ? <DungeonActionBar {...actionBarProps} /> : null}
            overlays={
                <>
            {isMissionInitialized &&
                !gameSession?.isHeroOrderConfirmed &&
                (gameSession?.heroes?.length || 0) > 1 && (
                <DungeonHeroOrder
                    heroes={gameSession?.heroes || []}
                    onConfirmOrder={handleConfirmHeroOrder}
                />
            )}

            {gameSession?.isHeroOrderConfirmed &&
                isSpellSelectionRequired &&
                spellSelectionHeroes.length > 0 && (
                <DungeonSpellSelectionModal
                    heroes={spellSelectionHeroes}
                    allSpells={staticSpells}
                    onConfirmSelection={confirmSpellSelection}
                />
            )}

            {gameSession?.lastAttack && (
                <CombatResultModal
                    isOpen={true}
                    onClose={closeCombatResult}
                    combatResult={gameSession.lastAttack.combatResult}
                    attacker={gameSession.lastAttack.hero}
                    defender={gameSession.lastAttack.monster}
                />
            )}

            {notificationMessage && (
                <DungeonNotification
                    message={notificationMessage}
                    onClose={() => setNotificationMessage(null)}
                />
            )}

            <DungeonScriptDialog
                open={scriptDialogQueue.length > 0}
                message={scriptDialogQueue[0] ?? ''}
                onClose={() => setScriptDialogQueue((q) => q.slice(1))}
            />

            {drawnTreasureCard && (
                <TreasureCardModal
                    isOpen={true}
                    card={drawnTreasureCard}
                    onClose={closeTreasureCardModal}
                />
            )}

            {isInventoryOpen && (
                <DungeonInventoryModal
                    isOpen={isInventoryOpen}
                    hero={currentHero}
                    allItems={staticItems}
                    allEquipment={staticEquipment}
                    onToggleEquip={(heroId, itemId) => hooksInventoryLogic.toggleEquipItem(heroId, itemId, gameSession)}
                    onUseItem={handleUseItem}
                    onClose={() => setIsInventoryOpen(false)}
                />
            )}

            {isSpellCastModalOpen && (
                <DungeonSpellCastModal
                    isOpen={isSpellCastModalOpen}
                    hero={currentHero}
                    allSpells={staticSpells}
                    onCastSpell={handleCastSpell}
                    onClose={() => setIsSpellCastModalOpen(false)}
                />
            )}

            {isMissionSummaryOpen && (
                <DungeonMissionSummary
                    isOpen={isMissionSummaryOpen}
                    heroes={gameSession?.heroes || []}
                    allEquipment={staticEquipment}
                    allItems={staticItems}
                    onClose={completeMission}
                />
            )}

            {isGameOverOpen && (
                <DungeonGameOver
                    isOpen={isGameOverOpen}
                    onExit={handleGameOverExit}
                />
            )}
                </>
            }
        />
    );
}