/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * ----------------------------------
 * This file was generated by ISL Compiler.
 * Source: dungeon-board.isl.md
 * Edit the ISL file instead.
 */

import React, { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { useDungeonFurniture } from "./dungeon-use-furniture";
import { useDungeonDoors } from "./dungeon-use-doors";
import { useDungeonVisibleMonsters } from "./dungeon-use-visible-monsters";
import { furnitureFlipStyle, doorPlaceholderStyleFromFilename } from "./furniture-flip";
import {
  DUNGEON_BOARD_COLS,
  DUNGEON_BOARD_ROWS,
  DUNGEON_CELL_SIZE,
  DUNGEON_BOARD_WIDTH,
  DUNGEON_BOARD_HEIGHT,
} from "./dungeon-board-constants.js";

const MONSTER_ATTACK_CURSOR = "url('/img/cursors/attack.svg') 16 16, crosshair";

function rosterSignature(session) {
  if (!session?.currentMap) return "";
  const hid = (session.heroes || [])
    .map((h) => String(h.heroId))
    .sort()
    .join(",");
  const mid = (session.monsters || [])
    .map((m) => String(m.id))
    .sort()
    .join(",");
  const g0 = session.currentMap.grid?.[0];
  return [hid, mid, g0?.x ?? "", g0?.y ?? "", (session.heroes || []).length, (session.monsters || []).length].join(
    "|"
  );
}

function buildVitalsSnapshot(session) {
  if (!session) return null;
  const heroes = new Map();
  for (const h of session.heroes || []) {
    heroes.set(String(h.heroId), {
      body: h.currentBody ?? 0,
      mind: h.currentMind ?? 0,
      x: h.x,
      y: h.y,
    });
  }
  const monsters = new Map();
  for (const m of session.monsters || []) {
    monsters.set(String(m.id), {
      body: m.currentBody ?? 0,
      mind: m.currentMind ?? 0,
      x: m.x,
      y: m.y,
    });
  }
  return { heroes, monsters };
}

export default function DungeonBoard({
  gameSession,
  boardVisibilityMap,
  onCellClick,
  onCellHover,
  onMonsterClick,
  hoveredPath = [],
  hoveredPathVariant = null,
  movementReachableCells = [],
  secretPassages = [],
  treasures = [],
  triggeredTraps = [],
  targetingSpell = null,
  targetingItem = null,
  visibilityCalc,
  canAttackMonsterAt
}) {
  const [hoveredCell, setHoveredCell] = useState(null);
  const [isLoaded, setIsLoaded] = useState(false);
  const [floatingNumbers, setFloatingNumbers] = useState([]);
  const prevRosterSigRef = useRef("");
  const prevVitalsRef = useRef(null);
  const floatSeqRef = useRef(0);

  const { visibleFurniture } = useDungeonFurniture({ gameSession, boardVisibilityMap });
  const { visibleDoors } = useDungeonDoors({ gameSession, boardVisibilityMap });
  const { visibleMonsters } = useDungeonVisibleMonsters({ gameSession, boardVisibilityMap });

  useEffect(() => {
    if (boardVisibilityMap) {
      setIsLoaded(true);
    }
  }, [boardVisibilityMap]);

  const activeHero = useMemo(() => {
    return gameSession?.heroes?.find(
      h => h.turnOrder === gameSession?.currentTurn && (h.currentBody || 0) > 0
    );
  }, [gameSession?.heroes, gameSession?.currentTurn]);

  const visibilityLookup = useMemo(() => {
    const map = new Map();
    if (boardVisibilityMap?.data) {
      boardVisibilityMap.data.forEach(c => map.set(`${c.x},${c.y}`, c.fog));
    }
    return map;
  }, [boardVisibilityMap]);

  const isFogged = useCallback((x, y) => {
    const key = `${x},${y}`;
    return visibilityLookup.has(key) ? visibilityLookup.get(key) : true;
  }, [visibilityLookup]);

  useEffect(() => {
    if (!gameSession) return;
    const sig = rosterSignature(gameSession);
    const nextSnap = buildVitalsSnapshot(gameSession);
    if (prevRosterSigRef.current !== sig) {
      prevRosterSigRef.current = sig;
      prevVitalsRef.current = nextSnap;
      setFloatingNumbers([]);
      return;
    }
    const prevSnap = prevVitalsRef.current;
    prevVitalsRef.current = nextSnap;
    if (!prevSnap) return;

    const pending = [];

    const pushFloat = (x, y, stat, delta) => {
      if (delta === 0 || x == null || y == null) return;
      if (isFogged(x, y)) return;
      floatSeqRef.current += 1;
      const key = `f-${floatSeqRef.current}`;
      const heal = delta > 0;
      const text = heal ? `+${delta}` : `${delta}`;
      const kind = heal ? "heal" : "dmg";
      pending.push({ key, x, y, text, stat, kind });
    };

    for (const [id, cur] of nextSnap.heroes) {
      const old = prevSnap.heroes.get(id);
      if (!old) continue;
      pushFloat(cur.x, cur.y, "body", cur.body - old.body);
      pushFloat(cur.x, cur.y, "mind", cur.mind - old.mind);
    }

    for (const [id, cur] of nextSnap.monsters) {
      const old = prevSnap.monsters.get(id);
      if (!old) continue;
      pushFloat(cur.x, cur.y, "body", cur.body - old.body);
      pushFloat(cur.x, cur.y, "mind", cur.mind - old.mind);
    }

    if (pending.length === 0) return;
    setFloatingNumbers((prev) => [...prev, ...pending]);
    pending.forEach((p) => {
      window.setTimeout(() => {
        setFloatingNumbers((prev) => prev.filter((f) => f.key !== p.key));
      }, 1300);
    });
  }, [gameSession, isFogged]);

  const handleCellClick = useCallback((x, y) => {
    onCellClick?.(x + 1, y + 1);
  }, [onCellClick]);

  const handleCellHover = useCallback((x, y) => {
    setHoveredCell({ x, y });
    onCellHover?.(x + 1, y + 1);
  }, [onCellHover]);

  const handleMouseLeaveBoard = useCallback(() => {
    setHoveredCell(null);
  }, []);

  const handleHeroTargetHover = useCallback((hero) => {
    if (targetingSpell?.targetType === "Hero") {
      setHoveredCell({ x: hero.x - 1, y: hero.y - 1 });
      onCellHover?.(hero.x, hero.y);
    }
  }, [targetingSpell, onCellHover]);

  const handleHeroTargetClick = useCallback((hero, e) => {
    e.stopPropagation();
    if (targetingSpell?.targetType === "Hero") {
      onCellClick?.(hero.x, hero.y);
    }
  }, [targetingSpell, onCellClick]);

  const handleMonsterHover = useCallback(
    (monster) => {
      if (!targetingSpell || !monster) return;
      const isMonsterSpell =
        targetingSpell.targetType === "Monster" || targetingSpell.effetto === "Genio";
      if (!isMonsterSpell) return;
      setHoveredCell({ x: monster.x - 1, y: monster.y - 1 });
      onCellHover?.(monster.x, monster.y);
    },
    [targetingSpell, onCellHover]
  );

  const gridCells = useMemo(() => {
    const cells = [];
    for (let y = 0; y < DUNGEON_BOARD_ROWS; y++) {
      for (let x = 0; x < DUNGEON_BOARD_COLS; x++) {
        cells.push({ x, y });
      }
    }
    return cells;
  }, []);

  const getCursorClass = useCallback((x, y) => {
    if (!targetingSpell) return "cursor-pointer";
    if (targetingSpell.targetType === "Point" || targetingSpell.targetType === "Door" || targetingSpell.effetto === "Genio") {
      return "cursor-crosshair";
    }
    return "cursor-default";
  }, [targetingSpell]);

  const getMonsterCursorStyle = useCallback(
    (m) => {
      if (targetingItem) {
        return { cursor: "crosshair" };
      }
      if (targetingSpell) {
        const isMonsterSpell =
          targetingSpell.targetType === "Monster" || targetingSpell.effetto === "Genio";
        if (!isMonsterSpell) {
          return { cursor: "not-allowed" };
        }
        if (!activeHero) {
          return { cursor: "not-allowed" };
        }
        const hasLos = visibilityCalc?.hasLineOfSight(
          activeHero.x,
          activeHero.y,
          m.x,
          m.y
        );
        return {
          cursor: hasLos ? MONSTER_ATTACK_CURSOR : "not-allowed"
        };
      }
      if (typeof canAttackMonsterAt === "function") {
        try {
          const ok = canAttackMonsterAt(m.id);
          return {
            cursor: ok ? MONSTER_ATTACK_CURSOR : "not-allowed"
          };
        } catch {
          return { cursor: "pointer" };
        }
      }
      return { cursor: "pointer" };
    },
    [targetingItem, targetingSpell, activeHero, visibilityCalc, canAttackMonsterAt]
  );

  return (
    <div
      className="relative overflow-hidden select-none touch-manipulation"
      style={{ width: DUNGEON_BOARD_WIDTH, height: DUNGEON_BOARD_HEIGHT }}
      onMouseLeave={handleMouseLeaveBoard}
    >
      <style>
        {`
          @keyframes mist1 {
            0% { transform: translate3d(-28px, -18px, 0); }
            50% { transform: translate3d(16px, 12px, 0); }
            100% { transform: translate3d(34px, -20px, 0); }
          }
          @keyframes mist2 {
            0% { transform: rotate(180deg) translate3d(-32px, 18px, 0); }
            50% { transform: rotate(180deg) translate3d(14px, -12px, 0); }
            100% { transform: rotate(180deg) translate3d(30px, 22px, 0); }
          }
          @keyframes dungeon-tile-reveal-pop {
            0% { opacity: 0; transform: scale(0.35); }
            65% { opacity: 1; transform: scale(1.1); }
            100% { opacity: 1; transform: scale(1); }
          }
          @keyframes dungeon-tile-glow-treasure {
            0%, 100% { filter: drop-shadow(0 0 3px rgba(234, 179, 8, 0.45)); }
            50% { filter: drop-shadow(0 0 8px rgba(250, 204, 21, 0.75)); }
          }
          @keyframes dungeon-tile-glow-trap {
            0%, 100% { filter: drop-shadow(0 0 3px rgba(220, 38, 38, 0.5)); }
            50% { filter: drop-shadow(0 0 7px rgba(249, 115, 22, 0.65)); }
          }
          @keyframes dungeon-tile-glow-passage {
            0%, 100% { filter: drop-shadow(0 0 3px rgba(6, 182, 212, 0.55)); }
            50% { filter: drop-shadow(0 0 8px rgba(168, 85, 247, 0.55)); }
          }
          .dungeon-board-special-tile-treasure {
            animation: dungeon-tile-reveal-pop 0.55s cubic-bezier(0.34, 1.45, 0.64, 1) forwards,
              dungeon-tile-glow-treasure 2.6s ease-in-out 0.55s infinite;
            transform-origin: center center;
          }
          .dungeon-board-special-tile-trap {
            animation: dungeon-tile-reveal-pop 0.55s cubic-bezier(0.34, 1.45, 0.64, 1) forwards,
              dungeon-tile-glow-trap 2.4s ease-in-out 0.55s infinite;
            transform-origin: center center;
          }
          .dungeon-board-special-tile-passage {
            animation: dungeon-tile-reveal-pop 0.55s cubic-bezier(0.34, 1.45, 0.64, 1) forwards,
              dungeon-tile-glow-passage 2.8s ease-in-out 0.55s infinite;
            transform-origin: center center;
          }
          @media (prefers-reduced-motion: reduce) {
            .dungeon-board-special-tile-treasure,
            .dungeon-board-special-tile-trap,
            .dungeon-board-special-tile-passage {
              animation: none;
              opacity: 1;
              transform: none;
              filter: none;
            }
            .dungeon-board-fog-overlay {
              transition: none !important;
            }
            .dungeon-board-float-number {
              animation: none !important;
              opacity: 1;
              transform: translate(-50%, -10px) scale(1);
            }
          }
          @keyframes dungeon-float-rise {
            0% { opacity: 0; transform: translate(-50%, 10px) scale(0.82); }
            15% { opacity: 1; transform: translate(-50%, -2px) scale(1.08); }
            100% { opacity: 0; transform: translate(-50%, -40px) scale(1); }
          }
          .dungeon-board-float-number {
            animation: dungeon-float-rise 1.12s cubic-bezier(0.22, 1, 0.36, 1) forwards;
            pointer-events: none;
            text-shadow: 0 1px 2px rgba(0, 0, 0, 0.95), 0 0 10px rgba(0, 0, 0, 0.6);
            font-weight: 800;
            font-size: 13px;
            line-height: 1;
            white-space: nowrap;
            z-index: 1;
          }
        `}
      </style>

      {/* Board Background */}
      <img 
        src="/img/tabellone/default.bmp" 
        alt="Game Board" 
        className="absolute inset-0 w-full h-full object-cover z-0"
      />

      {/* Ambient Grading */}
      <div className="absolute inset-0 pointer-events-none z-[5] bg-[radial-gradient(circle_at_center,rgba(251,191,36,0.05)_0%,rgba(0,0,0,0.4)_100%)]" />

      {/* Grid & Fog Layer */}
      <div
        className="absolute inset-0 grid z-10"
        style={{
          gridTemplateColumns: `repeat(${DUNGEON_BOARD_COLS}, ${DUNGEON_CELL_SIZE}px)`,
          gridTemplateRows: `repeat(${DUNGEON_BOARD_ROWS}, ${DUNGEON_CELL_SIZE}px)`,
        }}
      >
        {gridCells.map((cell) => {
          const fog = isFogged(cell.x + 1, cell.y + 1);
          const isHovered = hoveredCell?.x === cell.x && hoveredCell?.y === cell.y;
          const inPath = hoveredPath?.some(p => p.x === cell.x + 1 && p.y === cell.y + 1);
          const mapX = cell.x + 1;
          const mapY = cell.y + 1;
          const isReachable =
            !fog &&
            movementReachableCells?.some((p) => p.x === mapX && p.y === mapY);
          
          let highlightClass = "";
          
          if (inPath) {
            highlightClass = hoveredPathVariant === "valid" ? "bg-green-500/40" : "bg-red-500/40";
          } else if (isReachable && !targetingSpell) {
            highlightClass = "bg-emerald-500/30 ring-1 ring-inset ring-emerald-400/45";
          }

          if (targetingSpell && isHovered) {
            const hasMonster = visibleMonsters?.some(m => m.x === cell.x + 1 && m.y === cell.y + 1);
            const isClosedDoor = gameSession?.currentMap?.porte?.some(d => d.x === cell.x + 1 && d.y === cell.y + 1) && !gameSession?.openedDoors?.includes(`${cell.x + 1},${cell.y + 1}`);
            const hasHero = gameSession?.heroes?.some(h => h.x === cell.x + 1 && h.y === cell.y + 1);

            if (targetingSpell.effetto === "Genio" && (hasMonster || isClosedDoor)) {
              highlightClass = "bg-blue-500/30 animate-pulse border border-blue-500";
            } else {
              let isValidTarget = false;
              if (targetingSpell.targetType === "Point") isValidTarget = true;
              if (targetingSpell.targetType === "Door" && isClosedDoor) isValidTarget = true;
              if (targetingSpell.targetType === "Monster" && hasMonster) isValidTarget = true;
              if (targetingSpell.targetType === "Hero" && hasHero) isValidTarget = true;

              if (isValidTarget) {
                const hasLOS = activeHero && visibilityCalc?.hasLineOfSight(activeHero.x, activeHero.y, cell.x + 1, cell.y + 1);
                highlightClass = hasLOS ? "bg-blue-400/50" : "bg-red-500/40";
              }
            }
          }

          return (
            <div
              key={`cell-${cell.x}-${cell.y}`}
              className={`relative ${getCursorClass(cell.x, cell.y)}`}
              style={{ width: DUNGEON_CELL_SIZE, height: DUNGEON_CELL_SIZE }}
              onClick={() => handleCellClick(cell.x, cell.y)}
              onMouseEnter={() => handleCellHover(cell.x, cell.y)}
            >
              <div
                className="dungeon-board-fog-overlay absolute inset-0 bg-black pointer-events-none transition-opacity duration-300 ease-out"
                style={{ opacity: fog ? 1 : 0 }}
              />
              {highlightClass && <div className={`absolute inset-0 ${highlightClass}`} />}
            </div>
          );
        })}
      </div>

      {/* Global Mist Layers */}
      <div 
        className="absolute -top-[100px] -left-[100px] w-[calc(100%+200px)] h-[calc(100%+200px)] opacity-10 pointer-events-none z-20" 
        style={{ 
          backgroundImage: 'url(/img/mist.jpeg)', 
          backgroundRepeat: 'no-repeat', 
          backgroundPosition: 'center', 
          backgroundSize: '100% 100%', 
          animation: 'mist1 14s ease-in-out infinite alternate' 
        }} 
      />
      <div 
        className="absolute -top-[100px] -left-[100px] w-[calc(100%+200px)] h-[calc(100%+200px)] opacity-10 pointer-events-none z-20" 
        style={{ 
          backgroundImage: 'url(/img/mist.jpeg)', 
          backgroundRepeat: 'no-repeat', 
          backgroundPosition: 'center', 
          backgroundSize: '100% 100%', 
          animation: 'mist2 18s ease-in-out infinite alternate' 
        }} 
      />

      {/* Entities Layer */}
      <div className="absolute inset-0 pointer-events-none z-30">
        {/* Doors Above Fog Layer */}
        {visibleDoors?.map((d, i) => (
          <img
            key={`door-${i}`}
            src={`/img/cell/${d.img}`}
            className="absolute h-[34px] w-[34px] drop-shadow-md pointer-events-none"
            style={{
              left: (d.x - 1) * 34,
              top: (d.y - 1) * 34,
              ...doorPlaceholderStyleFromFilename(d.img),
            }}
            alt="Door"
          />
        ))}

        {/* Furniture */}
        {visibleFurniture?.map((f, i) => (
          <img
            key={`furn-${i}`}
            src={`/img/mobili/${f.img}`}
            className="absolute drop-shadow-md"
            style={{ left: (f.x - 1) * 34, top: (f.y - 1) * 34, ...furnitureFlipStyle(f.flpo, f.flpv) }}
            alt="Furniture"
          />
        ))}

        {/* Secret Passages */}
        {secretPassages?.map((sp, i) => (
          <div
            key={`sp-${i}`}
            className="dungeon-board-special-tile-passage pointer-events-none absolute flex items-center justify-center"
            style={{ left: (sp.x - 1) * 34, top: (sp.y - 1) * 34, width: 34, height: 34 }}
          >
            <img
              src={`/img/cell/${sp.img}`}
              className="max-h-[34px] max-w-[34px] drop-shadow-md"
              style={furnitureFlipStyle(sp.flpo, sp.flpv)}
              alt="Secret Passage"
            />
          </div>
        ))}

        {/* Treasures */}
        {treasures?.map((t, i) => (
          <div
            key={`trs-${i}`}
            className="dungeon-board-special-tile-treasure pointer-events-none absolute flex items-center justify-center"
            style={{ left: (t.x - 1) * 34, top: (t.y - 1) * 34, width: 34, height: 34 }}
          >
            <img src={`/img/cell/${t.img}`} className="max-h-[34px] max-w-[34px] drop-shadow-md" alt="Treasure" />
          </div>
        ))}

        {/* Traps */}
        {triggeredTraps?.map((t, i) => {
          let src = "";
          if (t.tipo === 1) src = "/img/cell/caduta.png";
          else if (t.tipo === 2) src = "/img/cell/lancia.png";
          else if (t.tipo === 3) src = "/img/cell/rocciacad.png";
          if (!src) return null;
          return (
            <div
              key={`trp-${i}`}
              className="dungeon-board-special-tile-trap pointer-events-none absolute flex items-center justify-center"
              style={{ left: (t.x - 1) * 34, top: (t.y - 1) * 34, width: 34, height: 34 }}
            >
              <img src={src} className="max-h-[34px] max-w-[34px] drop-shadow-md" alt="Trap" />
            </div>
          );
        })}

        {/* Script Images */}
        {gameSession?.scriptImages?.map((si, i) => {
          if (isFogged(si.x, si.y)) return null;
          return <img key={`scr-${i}`} src={si.src} className="absolute drop-shadow-md" style={{ left: (si.x - 1) * 34, top: (si.y - 1) * 34 }} alt="Script Overlay" />;
        })}
      </div>

      {/* Characters Layer */}
      <div className="absolute inset-0 pointer-events-none z-40">
        {/* Monsters */}
        {visibleMonsters?.map(m => {
          let effectClass = "";
          let effectOverlay = null;
          if (m.activeStatus?.includes("Sleep")) {
            effectClass = "ring-2 ring-blue-400 animate-pulse";
            effectOverlay = <div className="absolute -top-2 -right-2 text-xs font-bold text-blue-300 drop-shadow-md">Zzz</div>;
          } else if (m.activeStatus?.includes("Tempest")) {
            effectClass = "ring-2 ring-gray-400 animate-pulse";
          } else if (m.activeStatus?.includes("Entangled")) {
            effectOverlay = <div className="absolute inset-0 bg-green-500/30 rounded-full" style={{ backgroundImage: 'radial-gradient(circle, transparent 20%, #22c55e 100%)' }} />;
          }

          const monsterName = m.monster?.nome || "Mostro";
          const hpDisplay = `${m.currentBody}/${m.monster?.corpo || '?'}`;
          const mindDisplay = `${m.currentMind}/${m.monster?.mente || '?'}`;

          return (
            <div 
              key={`mon-${m.id}`}
              className="absolute pointer-events-auto"
              style={{
                left: (m.x - 1) * 34,
                top: (m.y - 1) * 34,
                width: 34,
                height: 34,
                ...getMonsterCursorStyle(m)
              }}
              onClick={() => onMonsterClick?.(m.id)}
              onMouseEnter={() => handleMonsterHover(m)}
              title={`${monsterName} - HP: ${hpDisplay} - Mind: ${mindDisplay}`}
            >
              <img src={`/img/mostri/${m.monster?.immagine}`} className={`max-w-[34px] drop-shadow-md ${effectClass}`} alt={monsterName} />
              <div className="absolute -bottom-2 -right-2 bg-red-600 text-white text-[10px] font-bold px-1 rounded-full border border-white shadow-sm tabular-nums pointer-events-none">
                {m.currentBody}
              </div>
              {effectOverlay}
            </div>
          );
        })}

        {/* Heroes */}
        {gameSession?.heroes?.filter(h => (h.currentBody || 0) > 0).map(h => {
          const isCurrentTurn = gameSession.currentTurn === h.turnOrder;
          const isTargeted = targetingSpell && targetingSpell.targetType === "Hero";
          const cursorClass = isTargeted ? 'cursor-crosshair' : 'cursor-default';

          let effectClass = "";
          if (h.activeStatus?.includes("FoggyMist")) effectClass += " opacity-50 ring-2 ring-white animate-pulse";
          if (h.activeStatus?.includes("RockSkin")) effectClass += " ring-2 ring-stone-500 animate-pulse";
          if (h.activeStatus?.includes("Courage")) effectClass += " ring-2 ring-orange-500 animate-pulse";
          if (h.activeStatus?.includes("WallPass")) effectClass += " ring-2 ring-amber-600 animate-pulse";
          if (h.activeStatus?.includes("InvisiblePassage")) effectClass += " ring-2 ring-cyan-400 animate-pulse";

          return (
            <div 
              key={`hero-${h.heroId}`}
              className={`absolute transition-all duration-300 ease-linear ${cursorClass} pointer-events-auto ${isCurrentTurn ? 'ring-2 ring-yellow-400 bg-yellow-400/20' : ''}`}
              style={{ left: (h.x - 1) * 34, top: (h.y - 1) * 34, width: 34, height: 34 }}
              onMouseEnter={() => handleHeroTargetHover(h)}
              onClick={(e) => handleHeroTargetClick(h, e)}
              title={`${h.hero?.classe || 'Eroe'} - HP: ${h.currentBody}/${h.hero?.corpo || '?'}`}
            >
              <img src={`/img/eroi/${h.hero?.miniature}`} className={`max-w-[34px] drop-shadow-md ${effectClass}`} alt="Hero" />
              <div className="absolute -bottom-2 -right-2 bg-red-600 text-white text-[10px] font-bold px-1 rounded-full border border-white shadow-sm">
                {h.currentBody}
              </div>
            </div>
          );
        })}
      </div>

      {/* Floating damage / heal numbers */}
      <div className="absolute inset-0 pointer-events-none z-[43]" aria-hidden>
        {floatingNumbers.map((f) => {
          const colorClass =
            f.stat === "body"
              ? f.kind === "heal"
                ? "text-green-300"
                : "text-red-200"
              : f.kind === "heal"
                ? "text-sky-300"
                : "text-violet-300";
          return (
            <div
              key={f.key}
              className={`dungeon-board-float-number absolute ${colorClass}`}
              style={{ left: (f.x - 1) * 34 + 17, top: (f.y - 1) * 34 }}
            >
              {f.text}
            </div>
          );
        })}
      </div>

      {/* Targeting Tracer */}
      {targetingSpell && hoveredCell && activeHero && (
        <svg className="absolute inset-0 w-full h-full pointer-events-none z-50">
          {(() => {
            const startX = (activeHero.x - 1) * 34 + 17;
            const startY = (activeHero.y - 1) * 34 + 17;
            const endX = hoveredCell.x * 34 + 17;
            const endY = hoveredCell.y * 34 + 17;
            const hasLOS = visibilityCalc?.hasLineOfSight(activeHero.x, activeHero.y, hoveredCell.x + 1, hoveredCell.y + 1);
            const isGenie = targetingSpell.effetto === "Genio";
            const color = isGenie || hasLOS ? "#3b82f6" : "#ef4444";

            return (
              <>
                <line x1={startX} y1={startY} x2={endX} y2={endY} stroke={color} strokeWidth="2" strokeDasharray="4 4" className="animate-pulse drop-shadow-[0_0_5px_rgba(59,130,246,0.8)]" />
                <circle cx={endX} cy={endY} r="10" stroke={color} strokeWidth="2" fill="none" className="animate-ping" />
                <circle cx={endX} cy={endY} r="4" fill={color} />
              </>
            );
          })()}
        </svg>
      )}

      {/* Immediate Attack Feedback */}
      {gameSession?.lastAttack && (
        <div className="absolute inset-0 pointer-events-none z-50">
          {gameSession.lastAttack.hero && (
            <div className="absolute w-[34px] h-[34px] rounded-full bg-orange-500/40 animate-ping" style={{ left: (gameSession.lastAttack.hero.x - 1) * 34, top: (gameSession.lastAttack.hero.y - 1) * 34 }} />
          )}
          {gameSession.lastAttack.monster && (
            <div className="absolute w-[34px] h-[34px]" style={{ left: (gameSession.lastAttack.monster.x - 1) * 34, top: (gameSession.lastAttack.monster.y - 1) * 34 }}>
              <div className="absolute inset-0 rounded-full border-4 border-red-500 animate-ping" />
            </div>
          )}
        </div>
      )}
    </div>
  );
}