/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * ----------------------------------
 * This file was generated by ISL Compiler.
 * Source: main-menu.isl.md
 * Edit the ISL file instead.
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { PageNavigationEnum } from './domain-core';

/** Set true when the map editor flow is ready for players. */
const SHOW_EDITOR_MENU = true;

/**
 * Generate deterministic-looking ember particles.
 * Random-but-stable positions/timings via simple LCG so different IDs never collide.
 */
function makeEmbers(count, seed = 1) {
  let s = seed >>> 0;
  const rand = () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return (s & 0xffffff) / 0xffffff;
  };
  const out = [];
  for (let i = 0; i < count; i++) {
    out.push({
      id: i,
      left: rand() * 100,
      size: 2 + rand() * 4,
      delay: -rand() * 14,
      duration: 9 + rand() * 12,
      drift: (rand() - 0.5) * 80,
      opacity: 0.35 + rand() * 0.45,
    });
  }
  return out;
}

export default function MainMenu({ onChangePageView = () => {} }) {
  const [isProcessing, setIsProcessing] = useState(false);
  const [activeItem, setActiveItem] = useState(PageNavigationEnum.PLAY_GAME);
  const [viewportHeight, setViewportHeight] = useState(
    typeof window !== 'undefined' ? window.innerHeight : 1080
  );

  const embers = useMemo(() => makeEmbers(28, 17), []);
  const isEditorActive = activeItem === PageNavigationEnum.EDITOR_GAME;

  // Capability: compactViewportResolution
  useEffect(() => {
    const handleResize = () => {
      if (typeof window !== 'undefined') {
        setViewportHeight(window.innerHeight);
      }
    };
    
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const isCompact = viewportHeight <= 720;
  const isUltraCompact = viewportHeight <= 460;

  // Capability: clickMenuItems
  const clickMenuItems = useCallback((destination) => {
    if (isProcessing) return;
    
    const validDestinations = Object.values(PageNavigationEnum);
    if (!validDestinations.includes(destination)) return;

    setIsProcessing(true);
    onChangePageView(destination);
  }, [isProcessing, onChangePageView]);

  // Capability: mouseOverMenuItems
  const mouseOverMenuItems = useCallback((destination) => {
    setActiveItem(destination);
  }, []);

  // Capability: clearPreviewState
  const clearPreviewState = useCallback(() => {
    setActiveItem(PageNavigationEnum.PLAY_GAME);
  }, []);

  // Menu Configuration Data
  const menuConfigFull = {
    [PageNavigationEnum.PLAY_GAME]: {
      id: PageNavigationEnum.PLAY_GAME,
      eyebrow: 'Campagna',
      title: 'GIOCA',
      teaser: 'Inizia o continua la tua avventura nel dungeon.',
      hint: 'Esplora le profondità',
      backdropClass: 'from-orange-900/25 via-red-950/15 to-transparent',
      activePill: 'Campagna',
    },
    [PageNavigationEnum.EDITOR_GAME]: {
      id: PageNavigationEnum.EDITOR_GAME,
      eyebrow: 'Forgia',
      title: 'EDITOR',
      teaser: 'Crea e modifica le tue mappe personalizzate.',
      hint: 'Plasma il mondo',
      backdropClass: 'from-slate-800/35 via-cyan-950/15 to-transparent',
      activePill: 'Forgia',
    }
  };

  const menuConfig = useMemo(() => {
    if (SHOW_EDITOR_MENU) return menuConfigFull;
    const { [PageNavigationEnum.EDITOR_GAME]: _, ...rest } = menuConfigFull;
    return rest;
  }, []);

  const visibleMenuItems = useMemo(() => Object.values(menuConfig), [menuConfig]);

  const currentConfig =
    menuConfig[activeItem] || menuConfig[PageNavigationEnum.PLAY_GAME];

  return (
    <div className="relative w-full h-screen overflow-hidden bg-transparent text-white font-sans select-none flex flex-col">
      
      {/* ActiveBackdropLayer: subtle tints; does not paint opaque black (global bg image stays visible) */}
      <div 
        className={`absolute inset-0 bg-gradient-to-br ${menuConfigFull[PageNavigationEnum.PLAY_GAME].backdropClass} transition-opacity duration-1000 z-0 ${activeItem === PageNavigationEnum.PLAY_GAME ? 'opacity-100' : 'opacity-0'}`}
      ></div>
      {SHOW_EDITOR_MENU && (
      <div 
        className={`absolute inset-0 bg-gradient-to-br ${menuConfigFull[PageNavigationEnum.EDITOR_GAME].backdropClass} transition-opacity duration-1000 z-0 ${activeItem === PageNavigationEnum.EDITOR_GAME ? 'opacity-100' : 'opacity-0'}`}
      ></div>
      )}

      {/* AtmosphereLayer: animated background fx (bracieri, nebbia, particelle, runa). */}
      <style>
        {`
          @keyframes mm-torch-flicker {
            0%   { opacity: 0.55; transform: scale(1); }
            35%  { opacity: 0.85; transform: scale(1.04); }
            55%  { opacity: 0.62; transform: scale(0.98); }
            80%  { opacity: 0.78; transform: scale(1.02); }
            100% { opacity: 0.55; transform: scale(1); }
          }
          @keyframes mm-mist-drift-l {
            0%   { transform: translate3d(-6%, 4%, 0) scale(1.1); }
            50%  { transform: translate3d(8%, -3%, 0) scale(1.18); }
            100% { transform: translate3d(-6%, 4%, 0) scale(1.1); }
          }
          @keyframes mm-mist-drift-r {
            0%   { transform: translate3d(4%, -2%, 0) scale(1.15); }
            50%  { transform: translate3d(-8%, 5%, 0) scale(1.05); }
            100% { transform: translate3d(4%, -2%, 0) scale(1.15); }
          }
          @keyframes mm-ember-rise {
            0%   { transform: translate3d(0, 0, 0) scale(0.6);    opacity: 0; }
            10%  { opacity: var(--mm-ember-opacity, 0.6); }
            70%  { opacity: var(--mm-ember-opacity, 0.6); }
            100% { transform: translate3d(var(--mm-ember-drift, 0px), -110vh, 0) scale(1.15); opacity: 0; }
          }
          @keyframes mm-rune-spin   { to { transform: rotate(360deg); } }
          @keyframes mm-rune-spin-r { to { transform: rotate(-360deg); } }
          @keyframes mm-glow-pulse {
            0%, 100% { opacity: 0.18; }
            50%      { opacity: 0.42; }
          }
          @media (prefers-reduced-motion: reduce) {
            .mm-anim { animation: none !important; }
          }
        `}
      </style>

      {/* Mist drifts — large radial blobs, very low opacity */}
      <div
        className="mm-anim absolute -inset-32 z-0 pointer-events-none opacity-[0.22] mix-blend-screen"
        style={{
          background:
            'radial-gradient(ellipse at 30% 60%, rgba(180, 120, 80, 0.45) 0%, rgba(0,0,0,0) 55%)',
          animation: 'mm-mist-drift-l 28s ease-in-out infinite',
          willChange: 'transform',
        }}
      />
      <div
        className="mm-anim absolute -inset-32 z-0 pointer-events-none opacity-[0.18] mix-blend-screen"
        style={{
          background:
            'radial-gradient(ellipse at 70% 35%, rgba(80, 140, 180, 0.4) 0%, rgba(0,0,0,0) 60%)',
          animation: 'mm-mist-drift-r 36s ease-in-out infinite',
          willChange: 'transform',
        }}
      />

      {/* Torch braziers in the lower corners — flicker with theme tint */}
      <div
        className="mm-anim absolute z-0 pointer-events-none rounded-full blur-2xl"
        style={{
          left: '-6rem',
          bottom: '-6rem',
          width: '28rem',
          height: '28rem',
          background:
            'radial-gradient(circle, rgba(251,146,60,0.5) 0%, rgba(251,146,60,0.0) 65%)',
          animation: 'mm-torch-flicker 3.6s ease-in-out infinite',
          mixBlendMode: 'screen',
          opacity: isEditorActive ? 0.35 : 0.7,
          transition: 'opacity 1s',
        }}
      />
      <div
        className="mm-anim absolute z-0 pointer-events-none rounded-full blur-2xl"
        style={{
          right: '-6rem',
          bottom: '-6rem',
          width: '28rem',
          height: '28rem',
          background: isEditorActive
            ? 'radial-gradient(circle, rgba(56,189,248,0.45) 0%, rgba(56,189,248,0) 65%)'
            : 'radial-gradient(circle, rgba(251,146,60,0.5) 0%, rgba(251,146,60,0) 65%)',
          animation: 'mm-torch-flicker 4.2s ease-in-out infinite 0.6s',
          mixBlendMode: 'screen',
          opacity: 0.65,
          transition: 'background 1s',
        }}
      />

      {/* Slow rotating arcane rune ring — barely visible, behind everything */}
      <div
        className="mm-anim absolute z-0 pointer-events-none left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 opacity-[0.06]"
        style={{
          width: 'min(82vh, 82vw)',
          height: 'min(82vh, 82vw)',
          border: '1px solid rgba(251,191,36,0.6)',
          borderRadius: '9999px',
          animation: 'mm-rune-spin 110s linear infinite',
        }}
      >
        <div
          className="absolute inset-6 rounded-full"
          style={{
            border: '1px dashed rgba(251,191,36,0.55)',
            animation: 'mm-rune-spin-r 80s linear infinite',
          }}
        />
        <div
          className="absolute inset-16 rounded-full"
          style={{
            border: '1px solid rgba(251,191,36,0.35)',
          }}
        />
      </div>

      {/* Pulsing center vignette */}
      <div
        className="mm-anim absolute inset-0 z-0 pointer-events-none"
        style={{
          backgroundImage:
            'radial-gradient(circle at 50% 50%, rgba(251, 146, 60, 0.10) 0%, transparent 55%)',
          animation: 'mm-glow-pulse 8s ease-in-out infinite',
        }}
      />

      {/* Floating embers / dust particles rising from the bottom */}
      <div className="absolute inset-0 z-0 pointer-events-none overflow-hidden">
        {embers.map((p) => (
          <span
            key={`ember-${p.id}`}
            className="mm-anim absolute rounded-full"
            style={{
              left: `${p.left}%`,
              bottom: '-8px',
              width: `${p.size}px`,
              height: `${p.size}px`,
              backgroundColor: isEditorActive
                ? 'rgba(125, 211, 252, 0.95)'
                : 'rgba(251, 191, 36, 0.95)',
              boxShadow: isEditorActive
                ? '0 0 8px 2px rgba(56,189,248,0.55)'
                : '0 0 8px 2px rgba(251,146,60,0.55)',
              opacity: 0,
              ['--mm-ember-drift']: `${p.drift}px`,
              ['--mm-ember-opacity']: p.opacity,
              animation: `mm-ember-rise ${p.duration}s linear ${p.delay}s infinite`,
              willChange: 'transform, opacity',
              transition: 'background-color 1s, box-shadow 1s',
            }}
          />
        ))}
      </div>

      {/* Main Content Container */}
      <div className="relative z-10 flex flex-col w-full h-full items-center">
        
        {/* HeaderPlaque */}
        <div className={`flex flex-col items-center text-center ${isUltraCompact ? 'mt-4 mb-2' : isCompact ? 'mt-8 mb-4' : 'mt-16 mb-8'}`}>
          <span className={`text-amber-600 tracking-[0.3em] font-semibold uppercase ${isUltraCompact ? 'text-xs' : 'text-sm'}`}>
            Portale del Regno
          </span>
          <h1 className={`font-serif font-bold tracking-wide text-gray-100 drop-shadow-lg ${isUltraCompact ? 'text-4xl' : isCompact ? 'text-6xl' : 'text-8xl'}`}>
            Dungeon
          </h1>
          {!isUltraCompact && (
            <p className={`text-gray-400 mt-3 ${isCompact ? 'text-sm' : 'text-base'}`}>
              Scegli il tuo percorso, eroe.
            </p>
          )}
        </div>

        {/* ActiveStatePill */}
        <div className={`flex justify-center transition-all duration-300 ${isUltraCompact ? 'mb-3' : 'mb-8'}`}>
          <div className={`rounded-full bg-black/60 border border-gray-700/50 flex items-center backdrop-blur-sm ${isUltraCompact ? 'px-3 py-1 space-x-2' : 'px-5 py-2 space-x-3'}`}>
            <span className={`text-amber-500 font-bold uppercase tracking-wider ${isUltraCompact ? 'text-[10px]' : 'text-xs'}`}>
              {currentConfig.activePill}
            </span>
            <div className="w-1 h-1 rounded-full bg-gray-600"></div>
            <span className={`text-gray-300 ${isUltraCompact ? 'text-[10px]' : 'text-xs'}`}>
              {currentConfig.hint}
            </span>
          </div>
        </div>

        {/* ActionArea + StatusPlaque (side by side from lg) */}
        <div
          className={`w-full max-w-7xl mx-auto flex gap-4 lg:gap-6 items-stretch ${
            isUltraCompact ? 'flex-row px-4' : 'flex-col md:flex-row px-6 md:px-12'
          }`}
        >
          <div
            className={`flex flex-1 min-w-0 gap-4 ${
              isUltraCompact ? 'flex-row' : 'flex-col md:flex-row'
            }`}
          >
            {visibleMenuItems.map((config) => (
              <button
                key={config.id}
                onClick={() => clickMenuItems(config.id)}
                onMouseEnter={() => mouseOverMenuItems(config.id)}
                onMouseLeave={clearPreviewState}
                onFocus={() => mouseOverMenuItems(config.id)}
                onBlur={clearPreviewState}
                disabled={isProcessing}
                className={`
                  group relative flex flex-col text-left border border-gray-800 bg-black/40 backdrop-blur-md
                  hover:bg-gray-900/80 hover:border-gray-600 transition-all duration-300 overflow-hidden
                  focus:outline-none focus:ring-2 focus:ring-amber-700/50
                  ${isUltraCompact ? 'flex-1 p-4 rounded-lg' : 'w-full md:w-1/2 p-8 rounded-2xl'}
                  ${activeItem === config.id ? 'border-gray-600 bg-gray-900/60 shadow-[0_0_30px_rgba(0,0,0,0.5)]' : ''}
                  ${isProcessing ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}
                `}
              >
                {/* Hover Glow Effect */}
                <div className={`absolute inset-0 bg-gradient-to-br ${config.backdropClass} opacity-0 group-hover:opacity-20 transition-opacity duration-500`}></div>
                
                <div className="relative z-10 flex flex-col h-full justify-center">
                  <span className={`text-amber-600 font-bold tracking-widest uppercase ${isUltraCompact ? 'text-[10px] mb-1' : 'text-xs mb-2'}`}>
                    {config.eyebrow}
                  </span>
                  <span className={`font-serif font-bold text-gray-100 ${isUltraCompact ? 'text-2xl' : isCompact ? 'text-4xl' : 'text-5xl'}`}>
                    {config.title}
                  </span>
                  
                  {!isUltraCompact && (
                    <span className={`text-gray-400 mt-3 ${isCompact ? 'text-sm' : 'text-base'}`}>
                      {config.teaser}
                    </span>
                  )}
                  
                  {!isUltraCompact && (
                    <div className={`mt-6 flex items-center text-amber-500 font-bold text-sm transition-all duration-300 ${activeItem === config.id ? 'opacity-100 translate-x-0' : 'opacity-0 -translate-x-4'}`}>
                      Entra <span className="ml-2 text-lg leading-none">→</span>
                    </div>
                  )}
                </div>
              </button>
            ))}
          </div>

          {/* StatusPlaque (Desktop only) */}
          <div className="hidden lg:flex flex-col shrink-0 w-56 xl:w-64 self-center p-6 bg-black/50 border border-gray-800/80 rounded-xl backdrop-blur-md transition-all duration-500">
            <span className="text-gray-500 text-[10px] font-bold uppercase tracking-widest mb-3">
              Scena attiva
            </span>
            <span className="text-gray-100 font-serif font-bold text-xl mb-1">
              {currentConfig.title}
            </span>
            <span className="text-gray-400 text-sm">
              {currentConfig.hint}
            </span>
          </div>
        </div>

      </div>
    </div>
  );
}